export { default as bold } from './bold/index'
export { default as italic } from './italic/index'
export { default as image } from './image/index'
export { default as color } from './color/index'
export { default as fontSize } from './fontSize/index'
