export { default as bold } from './bold/index'
export { default as italic } from './italic/index'
export { default as image } from './image/index'
export { default as video } from './video/index'
export { default as color } from './color/index'
export { default as fontSize } from './fontSize/index'
export { default as justifyLeft } from './justify/left'
export { default as justifyRight } from './justify/right'
export { default as justifyCenter } from './justify/center'
// export { default as JustifyRight } from './justify/right'
// export { default as JustifyCenter } from './justify/center'
